def paragons_skoda():

    choose = input("Number of paragons: ")
    if choose == '1':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)

    elif choose == '2':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)

    elif choose == '3':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)

    elif choose == '4':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)

    elif choose == '5':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)

    elif choose == '6':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)

    elif choose == '7':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)

    elif choose == '8':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)

    elif choose == '9':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)
        date8 = input("Enter a date of tank: ")
        start.wb13.active['B22'] = date8
        fuel8 = input("Enter amount of fuel: ")
        start.wb13.active['C22'] = int(fuel8)
        cost8 = input("Enter a fuel cost: ")
        start.wb13.active['E22'] = int(cost8)

    elif choose == '10':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)
        date8 = input("Enter a date of tank: ")
        start.wb13.active['B22'] = date8
        fuel8 = input("Enter amount of fuel: ")
        start.wb13.active['C22'] = int(fuel8)
        cost8 = input("Enter a fuel cost: ")
        start.wb13.active['E22'] = int(cost8)
        date9 = input("Enter a date of tank: ")
        start.wb13.active['B23'] = date9
        fuel9 = input("Enter amount of fuel: ")
        start.wb13.active['C23'] = int(fuel9)
        cost9 = input("Enter a fuel cost: ")
        start.wb13.active['E23'] = int(cost9)

    elif choose == '11':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)
        date8 = input("Enter a date of tank: ")
        start.wb13.active['B22'] = date8
        fuel8 = input("Enter amount of fuel: ")
        start.wb13.active['C22'] = int(fuel8)
        cost8 = input("Enter a fuel cost: ")
        start.wb13.active['E22'] = int(cost8)
        date9 = input("Enter a date of tank: ")
        start.wb13.active['B23'] = date9
        fuel9 = input("Enter amount of fuel: ")
        start.wb13.active['C23'] = int(fuel9)
        cost9 = input("Enter a fuel cost: ")
        start.wb13.active['E23'] = int(cost9)
        date10 = input("Enter a date of tank: ")
        start.wb13.active['B24'] = date10
        fuel10 = input("Enter amount of fuel: ")
        start.wb13.active['C24'] = int(fuel10)
        cost10 = input("Enter a fuel cost: ")
        start.wb13.active['E24'] = int(cost10)

    elif choose == '12':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)
        date8 = input("Enter a date of tank: ")
        start.wb13.active['B22'] = date8
        fuel8 = input("Enter amount of fuel: ")
        start.wb13.active['C22'] = int(fuel8)
        cost8 = input("Enter a fuel cost: ")
        start.wb13.active['E22'] = int(cost8)
        date9 = input("Enter a date of tank: ")
        start.wb13.active['B23'] = date9
        fuel9 = input("Enter amount of fuel: ")
        start.wb13.active['C23'] = int(fuel9)
        cost9 = input("Enter a fuel cost: ")
        start.wb13.active['E23'] = int(cost9)
        date10 = input("Enter a date of tank: ")
        start.wb13.active['B24'] = date10
        fuel10 = input("Enter amount of fuel: ")
        start.wb13.active['C24'] = int(fuel10)
        cost10 = input("Enter a fuel cost: ")
        start.wb13.active['E24'] = int(cost10)
        date11 = input("Enter a date of tank: ")
        start.wb13.active['B25'] = date11
        fuel11 = input("Enter amount of fuel: ")
        start.wb13.active['C25'] = int(fuel11)
        cost11 = input("Enter a fuel cost: ")
        start.wb13.active['E25'] = int(cost11)

    elif choose == '13':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)
        date8 = input("Enter a date of tank: ")
        start.wb13.active['B22'] = date8
        fuel8 = input("Enter amount of fuel: ")
        start.wb13.active['C22'] = int(fuel8)
        cost8 = input("Enter a fuel cost: ")
        start.wb13.active['E22'] = int(cost8)
        date9 = input("Enter a date of tank: ")
        start.wb13.active['B23'] = date9
        fuel9 = input("Enter amount of fuel: ")
        start.wb13.active['C23'] = int(fuel9)
        cost9 = input("Enter a fuel cost: ")
        start.wb13.active['E23'] = int(cost9)
        date10 = input("Enter a date of tank: ")
        start.wb13.active['B24'] = date10
        fuel10 = input("Enter amount of fuel: ")
        start.wb13.active['C24'] = int(fuel10)
        cost10 = input("Enter a fuel cost: ")
        start.wb13.active['E24'] = int(cost10)
        date11 = input("Enter a date of tank: ")
        start.wb13.active['B25'] = date11
        fuel11 = input("Enter amount of fuel: ")
        start.wb13.active['C25'] = int(fuel11)
        cost11 = input("Enter a fuel cost: ")
        start.wb13.active['E25'] = int(cost11)
        date12 = input("Enter a date of tank: ")
        start.wb13.active['B26'] = date12
        fuel12 = input("Enter amount of fuel: ")
        start.wb13.active['C26'] = int(fuel12)
        cost12 = input("Enter a fuel cost: ")
        start.wb13.active['E26'] = int(cost12)

    elif choose == '14':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)
        date8 = input("Enter a date of tank: ")
        start.wb13.active['B22'] = date8
        fuel8 = input("Enter amount of fuel: ")
        start.wb13.active['C22'] = int(fuel8)
        cost8 = input("Enter a fuel cost: ")
        start.wb13.active['E22'] = int(cost8)
        date9 = input("Enter a date of tank: ")
        start.wb13.active['B23'] = date9
        fuel9 = input("Enter amount of fuel: ")
        start.wb13.active['C23'] = int(fuel9)
        cost9 = input("Enter a fuel cost: ")
        start.wb13.active['E23'] = int(cost9)
        date10 = input("Enter a date of tank: ")
        start.wb13.active['B24'] = date10
        fuel10 = input("Enter amount of fuel: ")
        start.wb13.active['C24'] = int(fuel10)
        cost10 = input("Enter a fuel cost: ")
        start.wb13.active['E24'] = int(cost10)
        date11 = input("Enter a date of tank: ")
        start.wb13.active['B25'] = date11
        fuel11 = input("Enter amount of fuel: ")
        start.wb13.active['C25'] = int(fuel11)
        cost11 = input("Enter a fuel cost: ")
        start.wb13.active['E25'] = int(cost11)
        date12 = input("Enter a date of tank: ")
        start.wb13.active['B26'] = date12
        fuel12 = input("Enter amount of fuel: ")
        start.wb13.active['C26'] = int(fuel12)
        cost12 = input("Enter a fuel cost: ")
        start.wb13.active['E26'] = int(cost12)
        date13 = input("Enter a date of tank: ")
        start.wb13.active['B27'] = date13
        fuel13 = input("Enter amount of fuel: ")
        start.wb13.active['C27'] = int(fuel13)
        cost13 = input("Enter a fuel cost: ")
        start.wb13.active['E27'] = int(cost13)

    elif choose == '15':
        date = input("Enter a date of tank: ")
        start.wb13.active['B14'] = date
        fuel = input("Enter amount of fuel: ")
        start.wb13.active['C14'] = int(fuel)
        cost = input("Enter a fuel cost: ")
        start.wb13.active['E14'] = int(cost)
        date1 = input("Enter a date of tank: ")
        start.wb13.active['B15'] = date1
        fuel1 = input("Enter amount of fuel: ")
        start.wb13.active['C15'] = int(fuel1)
        cost1 = input("Enter a fuel cost: ")
        start.wb13.active['E15'] = int(cost1)
        date2 = input("Enter a date of tank: ")
        start.wb13.active['B16'] = date2
        fuel2 = input("Enter amount of fuel: ")
        start.wb13.active['C16'] = int(fuel2)
        cost2 = input("Enter a fuel cost: ")
        start.wb13.active['E16'] = int(cost2)
        date3 = input("Enter a date of tank: ")
        start.wb13.active['B17'] = date3
        fuel3 = input("Enter amount of fuel: ")
        start.wb13.active['C17'] = int(fuel3)
        cost3 = input("Enter a fuel cost: ")
        start.wb13.active['E17'] = int(cost3)
        date4 = input("Enter a date of tank: ")
        start.wb13.active['B18'] = date4
        fuel4 = input("Enter amount of fuel: ")
        start.wb13.active['C18'] = int(fuel4)
        cost4 = input("Enter a fuel cost: ")
        start.wb13.active['E18'] = int(cost4)
        date5 = input("Enter a date of tank: ")
        start.wb13.active['B19'] = date5
        fuel5 = input("Enter amount of fuel: ")
        start.wb13.active['C19'] = int(fuel5)
        cost5 = input("Enter a fuel cost: ")
        start.wb13.active['E19'] = int(cost5)
        date6 = input("Enter a date of tank: ")
        start.wb13.active['B20'] = date6
        fuel6 = input("Enter amount of fuel: ")
        start.wb13.active['C20'] = int(fuel6)
        cost6 = input("Enter a fuel cost: ")
        start.wb13.active['E20'] = int(cost6)
        date7 = input("Enter a date of tank: ")
        start.wb13.active['B21'] = date7
        fuel7 = input("Enter amount of fuel: ")
        start.wb13.active['C21'] = int(fuel7)
        cost7 = input("Enter a fuel cost: ")
        start.wb13.active['E21'] = int(cost7)
        date8 = input("Enter a date of tank: ")
        start.wb13.active['B22'] = date8
        fuel8 = input("Enter amount of fuel: ")
        start.wb13.active['C22'] = int(fuel8)
        cost8 = input("Enter a fuel cost: ")
        start.wb13.active['E22'] = int(cost8)
        date9 = input("Enter a date of tank: ")
        start.wb13.active['B23'] = date9
        fuel9 = input("Enter amount of fuel: ")
        start.wb13.active['C23'] = int(fuel9)
        cost9 = input("Enter a fuel cost: ")
        start.wb13.active['E23'] = int(cost9)
        date10 = input("Enter a date of tank: ")
        start.wb13.active['B24'] = date10
        fuel10 = input("Enter amount of fuel: ")
        start.wb13.active['C24'] = int(fuel10)
        cost10 = input("Enter a fuel cost: ")
        start.wb13.active['E24'] = int(cost10)
        date11 = input("Enter a date of tank: ")
        start.wb13.active['B25'] = date11
        fuel11 = input("Enter amount of fuel: ")
        start.wb13.active['C25'] = int(fuel11)
        cost11 = input("Enter a fuel cost: ")
        start.wb13.active['E25'] = int(cost11)
        date12 = input("Enter a date of tank: ")
        start.wb13.active['B26'] = date12
        fuel12 = input("Enter amount of fuel: ")
        start.wb13.active['C26'] = int(fuel12)
        cost12 = input("Enter a fuel cost: ")
        start.wb13.active['E26'] = int(cost12)
        date13 = input("Enter a date of tank: ")
        start.wb13.active['B27'] = date13
        fuel13 = input("Enter amount of fuel: ")
        start.wb13.active['C27'] = int(fuel13)
        cost13 = input("Enter a fuel cost: ")
        start.wb13.active['E27'] = int(cost13)
        date14 = input("Enter a date of tank: ")
        start.wb13.active['B28'] = date14
        fuel14 = input("Enter amount of fuel: ")
        start.wb13.active['C28'] = int(fuel14)
        cost14 = input("Enter a fuel cost: ")
        start.wb13.active['E28'] = int(cost14)

    start.wb13.save("3.SKODA FABIA 2.xlsx")
